name: Daily builds

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    environment: launchpad
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Fetch all history so we can push
          fetch-depth: 0

      - name: Setup git
        run: |
          git config user.name "CI Bot"
          git config user.email "nextcloud-snappy-bot@git.launchpad.net"
          git remote add deploy git+ssh://nextcloud-snappy-bot@git.launchpad.net/nextcloud-snap

      - name: Setup SSH
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup launchpad keys
        run: echo "${{ vars.LAUNCHPAD_SSH_PUBLIC_KEYS }}" > ~/.ssh/known_hosts

      - name: Spawn builds
        run: ./.github/spawn-dailies.sh
