name: Manage stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
      with:
        days-before-stale: 60
        days-before-close: 7
        exempt-issue-labels: feature,bug,dependency,security
        stale-issue-message: 'This issue is stale because it has been without activity for 60 days. It will be closed after 7 more days of inactivity.'
        stale-pr-message: 'This pull request is stale because it has been without activity for 60 days. It will be closed after 7 more days of inactivity.'
